---
- name: setup tomcat
  hosts: all
  become: true
  tasks: 
  - name: install java on RedHat
    yum: 
      name: java
      state: installed
    when: ansible_os_family == "RedHat"

  - name: install java on Ubuntu
    apt:
      name: default-jdk
      state: installed
    when:  ansible_os_family == "Ubuntu"

  - name: download
    get_url:
      url:  https://downloads.apache.org/tomcat/tomcat-8/v8.5.83/bin/apache-tomcat-8.5.83.tar.gz
      dest: /opt

  - name: extractin tar.gz file
    unarchive:
      src: /opt/apache-tomcat-8.5.83.tar.gz
      dest: /opt
      remote_src: true

  - name: changing permissions
    file:
      path: /opt/apache-tomcat-8.5.83/bin/startup.sh
      mode: 0777

  - name: starting tomcat service
    shell: nohup ./startup.sh
    args:
      chdir: /opt/apache-tomcat-8.5.83/bin/
