---
- name: My Test Playbook
  hosts: all
  become: true
  tasks: 
  - name: stop httpd service
    service:
      name: httpd
      state: stopped

  - name: uninstall httpd package
    yum: 
      name: httpd
      state: removed

